### ISSUE TITLE
Question: Covariance Function Parameters?

### ISSUE THREAD

**Issue by citibeth** [marionmari/pyGPs#51]
I'm trying to better understand the parameters `ell` and `sigma` for the kernel functions (eg: pyGPs.cov.RBF).  Can you please point do documentation or a description of these?  Thank you!

**Comment by shansfolder** [comment]
hi @citibeth , due to the change of university of Prof. Kersting (principle investor of pyGPs), the documentation is at the moment not hosted online.

Alternatively, you can use the local doc. Just ```git clone``` our source and open the files in this folder: https://github.com/marionmari/pyGPs/tree/master/doc/build/html

These pages are build via ```Sphinx```, so you are able the build it yourself as well.

**Comment by marionmari** [comment]
please also check the Gaussian Process for ML book for any conceptual/theory related questions.
